name: pokexplorer
description: "A Flutter-based project for interview purposes - Android only"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.1.003+11003

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.0

  lottie: ^3.1.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.14

  carousel_slider: ^5.0.0
  toastification: ^3.0.3
  flutter_launcher_icons: ^0.14.1
  percent_indicator: ^4.2.3
  url_launcher: ^6.3.1
  internet_connection_checker_plus: ^2.5.2
  sqflite: ^2.4.1
  path: ^1.9.0
  cached_network_svg_image: ^1.1.0
  animations: ^2.0.11

  iconsax_flutter: ^1.0.0
  get_it: ^8.0.3

  go_router: ^16.0.0
  dartz: ^0.10.1
  intl: ^0.20.2
  retrofit: ^4.6.0
  json_annotation: ^4.9.0




dev_dependencies:
  retrofit_generator: ^9.7.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4



  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon/icon.png" # only available for Android 8.0 devices and above

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # type icons from https://bulbapedia.bulbagarden.net/wiki/Type#Icons

  assets:
    - assets/images/
    - assets/svgs/
    - assets/lottieFiles/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
