name: pokexplorer
description: "A Flutter showcase project"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.3.002+13002

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.0
  lottie: ^3.1.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.14
  carousel_slider: ^5.0.0
  toastification: ^3.0.3
  flutter_launcher_icons: ^0.14.1
  percent_indicator: ^4.2.3
  url_launcher: ^6.3.2
  internet_connection_checker_plus: ^2.5.2
  sqflite: ^2.4.2
  path: ^1.9.0
  cached_network_svg_image: ^1.2.0
  animations: ^2.0.11
  iconsax_flutter: ^1.0.0
  get_it: ^8.0.3
  go_router: ^16.0.0
  dartz: ^0.10.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  http: ^1.4.0
  retry: ^3.1.2
  bloc_lint: ^0.2.1
  bloc_concurrency: ^0.3.0
  smooth_page_indicator: ^1.2.1
  audioplayers: ^6.5.0
  fluentui_system_icons: ^1.1.273


dev_dependencies:
  json_serializable: ^6.9.5
  build_runner: ^2.5.4



  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon/icon.png" # only available for Android 8.0 devices and above

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # type icons from https://bulbapedia.bulbagarden.net/wiki/Type#Icons

  assets:
    - assets/images/
    - assets/images/pokeballs/
    - assets/images/poke_types/
    - assets/svgs/
    - assets/lottieFiles/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700  
